name: Auto Restart Codespace if Stopped

on:
  schedule:
    - cron: "*/5 * * * *"   # check every 5 minutes
  workflow_dispatch:          # manual trigger

jobs:
  check-restart:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.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 }}" | gh auth login --with-token

      - name: Check Codespace Status and Restart if Needed
        run: |
          CODESPACE_NAME="teffective-train-wrjx95rrw4j6h9x5j"   # change this

          echo "🔍 Checking codespace: $CODESPACE_NAME..."
          STATUS=$(gh codespace list --json name,state | jq -r ".[] | select(.name==\"$CODESPACE_NAME\") | .state")

          if [ -z "$STATUS" ]; then
            echo "❌ Codespace $CODESPACE_NAME not found"
            exit 1
          fi

          echo "ℹ️ Current status: $STATUS"
          if [ "$STATUS" = "Stopped" ]; then
            echo "🔄 Restarting Codespace..."
            CODESPACE_ID=$(gh codespace list --json name,id | jq -r ".[] | select(.name==\"$CODESPACE_NAME\") | .id")
            gh api -X POST "user/codespaces/$CODESPACE_ID/restart"
            echo "✅ Restart request sent!"
          else
            echo "✅ Codespace is already running."
          fi
